groups:
  - name: group_one
    users:
      - user_one
      - user_one
    groups: 
      - group_two

  - name: group_two
    users: 
      - user_three

roles:
  - name: non_admin
    permissionset: psone
    modelset: msone

modelsets:
  - name: msone
    models:
      - modelone
      - modeltwo

permissionsets:
  - name: psone
    permissions:
      - permissionone
      - permissiontwo
